# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TestProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for TestProject
  # source https://github.com/hackiftekhar/IQKeyboardManager
  # Codeless drop-in universal library allows to prevent issues of keyboard sliding up and cover UITextField/UITextView.
  pod 'IQKeyboardManagerSwift'

  # Network abstraction layer written in Swift.
  # https://github.com/Moya/Moya
  # How use https://github.com/Moya/Moya/blob/master/docs/Examples/Basic.md
  pod 'Moya', '~> 12.0'
end
