# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestProject
  # source https://github.com/hackiftekhar/IQKeyboardManager
  # Codeless drop-in universal library allows to prevent issues of keyboard sliding up and cover UITextField/UITextView.
  pod 'IQKeyboardManagerSwift'

end
